-- 코드를 입력하세요
# SELECT USED_GOODS_BOARD.TITLE, USED_GOODS_BOARD.BOARD_ID,  USED_GOODS_REPLY.REPLY_ID, USED_GOODS_REPLY.WRITER_ID, USED_GOODS_REPLY.CONTENTS, DATE_FORMAT(USED_GOODS_REPLY.CREATED_DATE, "%Y-%m-%d") as CREATED_DATE
# from USED_GOODS_BOARD join USED_GOODS_REPLY
# where USED_GOODS_BOARD.BOARD_ID = USED_GOODS_REPLY.BOARD_ID and LEFT(USED_GOODS_REPLY.CREATED_DATE, 7) = "2022-10"
# order by USED_GOODS_REPLY.CREATED_DATE, USED_GOODS_BOARD.TITLE


SELECT TITLE, A.BOARD_ID, REPLY_ID, B.WRITER_ID, B.CONTENTS,  DATE_FORMAT(B.CREATED_DATE, '%Y-%m-%d')AS CREATED_DATE
FROM USED_GOODS_BOARD A, USED_GOODS_REPLY B
WHERE A.BOARD_ID = B.BOARD_ID
AND DATE_FORMAT(A.CREATED_DATE, '%Y-%m') = '2022-10'
ORDER BY B.CREATED_DATE ASC, TITLE ASC